-- Seed practice_questions with 250 questions
INSERT INTO practice_questions (category, difficulty, text, options, correct_index) VALUES
('influencers', 'medium', 'What did Andrew Tate claim he would do to Solana?', '["Pump it to $1000","Buy 51% of validators","Create a memecoin","Crash the entire network"]'::jsonb, 3),
('influencers', 'easy', 'How much did Andrew Tate reportedly lose trying to manipulate Solana?', '["$100K","$250K","$727K","$1M"]'::jsonb, 2),
('og_lore', 'hard', 'Where did Anatoly Yakovenko have his ''eureka moment'' for Proof of History?', '["Café Soleil at 4 AM","Starbucks","His garage","A hackathon"]'::jsonb, 0),
('og_lore', 'medium', 'What year did Solana mainnet beta launch?', '["2018","2019","2021","2020"]'::jsonb, 3),
('memecoins', 'easy', 'What was TRUMP memecoin''s peak market cap in 2026?', '["$1.2B","$2.8B","$5.37B","$10B"]'::jsonb, 2),
('defi', 'medium', 'What is Jupiter''s primary function?', '["Lending protocol","NFT marketplace","Staking pool","DEX aggregator"]'::jsonb, 3),
('defi', 'easy', 'Approximately how much daily volume does Jupiter process?', '["$50M","$700M","$200M","$2B"]'::jsonb, 1),
('memecoins', 'easy', 'Which platform hit $2B+ DEX volume ATH in 2026?', '["Pump.fun","Raydium","Orca","Meteora"]'::jsonb, 0),
('technical', 'hard', 'What consensus mechanism does Solana use alongside Proof of History?', '["Proof of Work","Proof of Stake","Tower BFT","Delegated PoS"]'::jsonb, 2),
('technical', 'medium', 'What is Solana''s theoretical maximum TPS?', '["10,000","400,000","65,000","1,000,000"]'::jsonb, 2),
('influencers', 'medium', 'Which influencer is known for predicting SOL''s rally from $8 to $200+?', '["Threadguy","Orangie","Jakey","Ansem"]'::jsonb, 3),
('influencers', 'easy', 'What is Ansem''s estimated net worth?', '["$5M","$10M","$50M","$20M+"]'::jsonb, 3),
('memecoins', 'medium', 'Which memecoin did Ansem heavily promote before its massive rally?', '["BONK","SAMO","MYRO","WIF"]'::jsonb, 3),
('memecoins', 'easy', 'What is Bonk''s approximate market cap?', '["$100M","$500M","$1B","$5B"]'::jsonb, 2),
('defi', 'medium', 'What is Meteora''s relationship to Jupiter?', '["Competitor","Subsidiary","Close ally","No relationship"]'::jsonb, 2),
('seeker', 'easy', 'How many free months of Helium Mobile do Seeker owners get?', '["1 month","3 months","6 months","12 months"]'::jsonb, 1),
('seeker', 'medium', 'Where MUST Seeker owners download Helium Mobile from to claim their free months?', '["Google Play Store","Apple App Store","Solana dApp Store","Helium website"]'::jsonb, 2),
('seeker', 'easy', 'How many Seeker devices have been shipped?', '["50,000","100,000","150,000","300,000"]'::jsonb, 2),
('seeker', 'medium', 'What percentage of SKR tokens are being airdropped to Seeker users?', '["30%","10%","20%","50%"]'::jsonb, 0),
('seeker', 'medium', 'When is the SKR token expected to launch?', '["January 2026","December 2025","March 2026","June 2026"]'::jsonb, 0),
('degen', 'easy', 'What does ''gm'' mean in crypto culture?', '["Good morning","Get money","Gonna moon","Give more"]'::jsonb, 0),
('degen', 'easy', 'What does ''WAGMI'' stand for?', '["We All Get Money Initially","We''re All Gonna Make It","Wallets Are Getting More Income","What A Great Memecoin Investment"]'::jsonb, 1),
('degen', 'medium', 'What does it mean to ''ape in''?', '["Sell everything","Buy impulsively without research","Hold forever","Stake tokens"]'::jsonb, 1),
('memecoins', 'hard', 'Pump.fun vs BonkFun: What was Pump.fun''s daily volume compared to BonkFun''s $8M?', '["$25M","$109M","$50M","$200M"]'::jsonb, 1),
('technical', 'hard', 'What is the average block time on Solana?', '["100ms","800ms","2 seconds","400ms"]'::jsonb, 3),
('og_lore', 'hard', 'Who co-founded Solana with Anatoly Yakovenko?', '["Sam Bankman-Fried","Andre Cronje","Do Kwon","Raj Gokal"]'::jsonb, 3),
('technical', 'medium', 'What programming language are Solana programs primarily written in?', '["JavaScript","Rust","Python","Solidity"]'::jsonb, 1),
('defi', 'easy', 'Which DEX was the first major one built on Solana?', '["Jupiter","Orca","Raydium","Meteora"]'::jsonb, 2),
('memecoins', 'medium', 'Which Andrew Tate token launched first?', '["RNT","TATE","COBRA","DADDY"]'::jsonb, 3),
('degen', 'easy', 'What does ''diamond hands'' mean?', '["Selling at a profit","Holding through volatility","Day trading","Buying the dip"]'::jsonb, 1),
('degen', 'easy', 'What are ''paper hands''?', '["Strong holders","NFT collectors","Early investors","Weak sellers who panic"]'::jsonb, 3),
('seeker', 'easy', 'How many dApps are available on the Solana dApp Store?', '["50+","225+","100+","500+"]'::jsonb, 1),
('seeker', 'medium', 'What is the total transaction volume processed through Seeker devices?', '["$1.8B","$500M","$1B","$5B"]'::jsonb, 0),
('technical', 'hard', 'What does PoH stand for in Solana''s architecture?', '["Proof of History","Proof of Hash","Proof of Holders","Protocol of Hashing"]'::jsonb, 0),
('og_lore', 'medium', 'Before Solana, Anatoly worked at which company?', '["Qualcomm","Google","Intel","Apple"]'::jsonb, 0),
('memecoins', 'easy', 'What animal is Bonk''s mascot?', '["Shiba Inu","Cat","Monkey","Dolphin"]'::jsonb, 0),
('degen', 'medium', 'What does ''rug pull'' mean?', '["A successful exit","Buying NFTs","Staking rewards","Developers abandoning a project and stealing funds"]'::jsonb, 3),
('technical', 'medium', 'What is a rent-exempt balance on Solana?', '["Free transactions","Minimum SOL to keep an account alive","Staking rewards","Validator fees"]'::jsonb, 1),
('defi', 'hard', 'What does JLP stand for in Jupiter?', '["Jupiter Liquidity Provider","Jupiter Lock Protocol","Jupiter Launch Pad","Jupiter Limit Protocol"]'::jsonb, 0),
('memecoins', 'medium', 'Which Solana memecoin was the first to reach $1B market cap?', '["WIF","SAMO","BONK","MYRO"]'::jsonb, 2),
('degen', 'easy', 'What does ''moon'' mean in crypto?', '["Price going extremely high","Price crashing","Lunar NFTs","Night trading"]'::jsonb, 0),
('degen', 'easy', 'What does ''rekt'' mean?', '["Making profit","Getting wrecked/losing money","Buying more","Staking"]'::jsonb, 1),
('technical', 'hard', 'How many validator nodes does Solana typically have active?', '["1,900+","100-200","500-800","5,000+"]'::jsonb, 0),
('og_lore', 'easy', 'What is Solana''s native token symbol?', '["SOLA","SLN","SOL","SOLANA"]'::jsonb, 2),
('influencers', 'medium', 'Which influencer is known for detailed crypto threads and educational content?', '["Ansem","Jakey","Threadguy","Supabased"]'::jsonb, 2),
('degen', 'medium', 'What does ''airdrop farming'' mean?', '["Growing crops on blockchain","Selling airdrops immediately","Using protocols hoping for future token rewards","NFT collecting"]'::jsonb, 2),
('memecoins', 'hard', 'What was the original supply of BONK at launch?', '["1 billion","100 billion","1 trillion","100 trillion"]'::jsonb, 3),
('technical', 'medium', 'What is the minimum SOL needed to create a wallet account?', '["0 SOL","0.00001 SOL","0.1 SOL","0.00089 SOL"]'::jsonb, 3),
('defi', 'medium', 'What does TVL stand for in DeFi?', '["Total Value Locked","Total Volume Loaded","Transaction Value Limit","Trading Value Level"]'::jsonb, 0),
('degen', 'easy', 'What does ''FOMO'' stand for?', '["Fear Of Missing Out","First On Market Only","Full Of Money Options","Flip Or Miss Out"]'::jsonb, 0),
('degen', 'easy', 'What does ''FUD'' stand for?', '["Fully Unified Decentralization","Fund Under Development","Fear, Uncertainty, and Doubt","Future Unstable Direction"]'::jsonb, 2),
('technical', 'hard', 'What is Solana''s Sealevel feature?', '["A DEX","Parallel smart contract runtime","A wallet","An NFT protocol"]'::jsonb, 1),
('og_lore', 'medium', 'What was Solana originally called during development?', '["Loom","Serum","It was always Solana","FastChain"]'::jsonb, 0),
('memecoins', 'easy', 'What does WIF stand for?', '["Wallet Integration File","dogwifhat","What Is Finance","Wrapped Index Fund"]'::jsonb, 1),
('defi', 'medium', 'Which protocol is known as the ''Uniswap of Solana''?', '["Orca","Serum","Meteora","Raydium"]'::jsonb, 3),
('technical', 'easy', 'What file extension do Solana wallets typically use?', '[".sol",".json",".wallet",".key"]'::jsonb, 1),
('degen', 'medium', 'What does ''exit liquidity'' mean?', '["Removing funds from a protocol","Becoming the buyer when whales dump","Adding liquidity","Early investor advantage"]'::jsonb, 1),
('influencers', 'hard', 'Which influencer is known for the phrase ''Solana SZN''?', '["Ansem","Orangie","Threadguy","Jakey"]'::jsonb, 0),
('memecoins', 'medium', 'What category of token is SAMO?', '["DeFi","NFT token","Gaming token","Dog memecoin"]'::jsonb, 3),
('technical', 'hard', 'What is Gulf Stream in Solana''s architecture?', '["A DEX protocol","Transaction forwarding protocol","Consensus mechanism","Token standard"]'::jsonb, 1),
('seeker', 'easy', 'What is Seeker''s primary function?', '["Mining device","Hardware wallet","NFT display","Web3 mobile phone"]'::jsonb, 3),
('degen', 'easy', 'What does ''hodl'' mean?', '["Hold On for Dear Life","Misspelling of ''hold''","Both A and B","High Output Digital Ledger"]'::jsonb, 2),
('technical', 'medium', 'What is the typical fee for a basic Solana transaction?', '["Free","0.01 SOL","0.000005 SOL","0.1 SOL"]'::jsonb, 2),
('og_lore', 'hard', 'What was the initial token sale price of SOL?', '["$0.04","$1.00","$5.00","$0.22"]'::jsonb, 3),
('defi', 'easy', 'What does AMM stand for in DeFi?', '["Advanced Money Management","Asset Migration Module","Algorithmic Mining Mechanism","Automatic Market Maker"]'::jsonb, 3),
('memecoins', 'medium', 'Which memecoin features a dog wearing a hat?', '["BONK","MYRO","WIF","SAMO"]'::jsonb, 2),
('degen', 'medium', 'What is ''alpha'' in crypto slang?', '["Inside information/early knowledge","First token","Testing phase","Market leader"]'::jsonb, 0),
('technical', 'hard', 'What is Turbine in Solana''s architecture?', '["Smart contract language","Block propagation protocol","Wallet standard","NFT protocol"]'::jsonb, 1),
('influencers', 'easy', 'Which social media platform is most popular for crypto influencers?', '["Facebook","Instagram","TikTok","X (Twitter)"]'::jsonb, 3),
('degen', 'easy', 'What does ''dump'' mean?', '["Buying heavily","Staking tokens","Selling large amounts","Creating liquidity"]'::jsonb, 2),
('technical', 'medium', 'What consensus does Solana use for finality?', '["Tower BFT","Proof of Work","Nakamoto Consensus","Casper"]'::jsonb, 0),
('memecoins', 'easy', 'What inspired the name ''dogwifhat''?', '["Elon Musk''s tweet","A cartoon character","A meme of a dog wearing a hat","Random generation"]'::jsonb, 2),
('og_lore', 'medium', 'When was Solana Labs founded?', '["2017","2019","2018","2020"]'::jsonb, 2),
('defi', 'hard', 'What was Serum DEX''s relationship to FTX?', '["No relationship","Built by FTX/Alameda","Competitor","Acquired by FTX"]'::jsonb, 1),
('degen', 'medium', 'What does ''ngmi'' stand for?', '["New Gamma Mining Index","Next Generation Market Increase","No Good Money Investment","Never Gonna Make It"]'::jsonb, 3),
('technical', 'easy', 'What format are Solana wallet addresses?', '["Hexadecimal (0x...)","Binary","Base58","Base64"]'::jsonb, 2),
('memecoins', 'hard', 'How many BONK tokens were airdropped at launch?', '["10% of supply","25% of supply","50% of supply","75% of supply"]'::jsonb, 2),
('seeker', 'medium', 'What blockchain does Helium Network use?', '["Ethereum","Solana","Polygon","Its own chain"]'::jsonb, 1),
('degen', 'easy', 'What does ''ser'' mean in crypto slang?', '["Misspelling of ''sir''","Service Error Report","Solana Exchange Rate","Security Enhancement Review"]'::jsonb, 0),
('technical', 'medium', 'What is an SPL token?', '["Solana Program Library token","Special Purpose Liquidity token","Staked Pool token","Solana Protocol Layer token"]'::jsonb, 0),
('og_lore', 'easy', 'What beach-related nickname is Solana sometimes given?', '["Solana Beach","Surf Chain","Beach Protocol","Sol Beach is the actual name"]'::jsonb, 0),
('defi', 'medium', 'What is Phoenix on Solana?', '["An order book DEX","A memecoin","An NFT marketplace","A wallet"]'::jsonb, 0),
('degen', 'hard', 'What does ''degen'' originally stand for?', '["Digital Generation","Decentralized Generator","Degenerate gambler","Development Genesis"]'::jsonb, 2),
('memecoins', 'medium', 'Which memecoin was named after Raj Gokal''s dog?', '["MYRO","BONK","SAMO","WIF"]'::jsonb, 0),
('technical', 'hard', 'What is Cloudbreak in Solana?', '["A wallet","Horizontally scaled state architecture","DEX protocol","NFT standard"]'::jsonb, 1),
('influencers', 'medium', 'Which influencer is known for orange-themed content?', '["Ansem","Threadguy","Jakey","Orangie"]'::jsonb, 3),
('degen', 'easy', 'What does ''pump'' mean?', '["Natural growth","Staking","Artificial price increase","Mining"]'::jsonb, 2),
('technical', 'medium', 'What does ''epoch'' mean on Solana?', '["Transaction batch","Block height","Token generation event","Time period for validator rotation (~2 days)"]'::jsonb, 3),
('seeker', 'hard', 'What processor does the Seeker device use?', '["Snapdragon 750","Snapdragon 888","Snapdragon 680","MediaTek Dimensity"]'::jsonb, 2),
('og_lore', 'medium', 'What beverage was Anatoly drinking during his PoH eureka moment?', '["Coffee","Red Bull","Tea","Water"]'::jsonb, 0),
('memecoins', 'easy', 'What platform is known for launching memecoins?', '["OpenSea","Pump.fun","Magic Eden","Tensor"]'::jsonb, 1),
('defi', 'easy', 'What is the main function of Orca?', '["Lending","DEX/Swap platform","Staking","NFT marketplace"]'::jsonb, 1),
('degen', 'medium', 'What does ''bag'' mean in crypto?', '["Wallet","Scam project","Holdings of a specific token","NFT collection"]'::jsonb, 2),
('technical', 'easy', 'What color is associated with Solana''s branding?', '["Green and purple","Blue","Orange","Red"]'::jsonb, 0),
('influencers', 'hard', 'Which influencer is known for ''supabased'' content?', '["Ansem","Jakey","Supabased","Threadguy"]'::jsonb, 2),
('degen', 'easy', 'What does ''shill'' mean?', '["Criticizing a project","Promoting a project","Selling a project","Creating a project"]'::jsonb, 1),
('technical', 'hard', 'What is Pipelining in Solana''s architecture?', '["Block creation method","Transaction processing optimization","Consensus mechanism","Token transfer protocol"]'::jsonb, 1),
('memecoins', 'medium', 'What was the controversy around TRUMP memecoin?', '["Rug pull","Failed launch","Wrong blockchain","Launched by president-elect with insider enrichment concerns"]'::jsonb, 3),
('og_lore', 'easy', 'Where is Solana Labs headquartered?', '["New York","San Francisco","Miami","Austin"]'::jsonb, 1),
('defi', 'medium', 'What is MarginFi on Solana?', '["DEX","NFT marketplace","Lending protocol","Wallet"]'::jsonb, 2),
('degen', 'hard', 'What does ''probably nothing'' mean sarcastically?', '["Literally nothing important","Actually something very bullish","A scam warning","Market correction"]'::jsonb, 1),
('technical', 'medium', 'What is the Solana token standard for NFTs?', '["Metaplex","ERC-721","SPL Token","BEP-721"]'::jsonb, 0),
('seeker', 'easy', 'What is the Saga phone?', '["Solana''s Web3 mobile phone","A gaming device","A hardware wallet","A tablet"]'::jsonb, 0),
('memecoins', 'easy', 'What does the BONK community call themselves?', '["Bonkers","Bonk Army","Bonk Nation","All of the above"]'::jsonb, 3),
('degen', 'easy', 'What does ''degen'' refer to?', '["Risk-taking crypto enthusiast","Conservative investor","Developer","Scammer"]'::jsonb, 0),
('technical', 'hard', 'What is Archivers in Solana''s architecture?', '["Validators","Nodes that store historical data","Transaction processors","Smart contract runners"]'::jsonb, 1),
('influencers', 'medium', 'Which influencer is known for detailed market analysis?', '["Jakey","Orangie","Ansem","Supabased"]'::jsonb, 2),
('og_lore', 'hard', 'How many years did it take from whitepaper to mainnet?', '["1 year","2 years","3 years","4 years"]'::jsonb, 1),
('defi', 'easy', 'What does ''yield farming'' mean?', '["Growing crops","Mining","Earning rewards by providing liquidity","Staking only"]'::jsonb, 2),
('degen', 'medium', 'What does ''10x'' mean?', '["10% gain","10-fold increase in price","10 transactions","10 times buying"]'::jsonb, 1),
('technical', 'medium', 'What wallet format does Phantom use?', '["Hardware","Paper","SMS","Browser extension"]'::jsonb, 3),
('memecoins', 'hard', 'What was the peak marketcap of WIF (dogwifhat)?', '["$500M","$1B","$2B","$4B+"]'::jsonb, 3),
('seeker', 'medium', 'What makes Seeker different from Saga?', '["Cheaper price point","Better specs","Different blockchain","Nothing"]'::jsonb, 0),
('degen', 'easy', 'What does ''buy the dip'' mean?', '["Buy at peak","Buy during price drops","Sell everything","Hold forever"]'::jsonb, 1),
('technical', 'easy', 'What is a Solana program?', '["A wallet app","Mining software","Browser extension","Smart contract"]'::jsonb, 3),
('og_lore', 'medium', 'What time did Anatoly wake up with the PoH idea?', '["2 AM","4 AM","6 AM","8 AM"]'::jsonb, 1),
('defi', 'hard', 'What is Drift Protocol?', '["DEX","Lending","Perpetuals trading platform","NFT marketplace"]'::jsonb, 2),
('memecoins', 'medium', 'What is the ticker for dogwifhat?', '["DOG","HAT","DWH","WIF"]'::jsonb, 3),
('degen', 'hard', 'What does ''few understand'' mean?', '["Complex topic","Educational content","Scam warning","Sarcastic way to say something is obvious but undervalued"]'::jsonb, 3),
('technical', 'medium', 'What is the maximum supply of SOL?', '["21 million","100 million","Uncapped/Inflationary","500 million"]'::jsonb, 2),
('seeker', 'easy', 'What network does Seeker primarily support?', '["Ethereum","Solana","Bitcoin","Polygon"]'::jsonb, 1),
('og_lore', 'hard', 'What was Anatoly''s role at Qualcomm?', '["Software engineer","CEO","Marketing","Sales"]'::jsonb, 0),
('defi', 'medium', 'What is Kamino Finance?', '["DEX","NFT platform","Wallet","Lending and liquidity protocol"]'::jsonb, 3),
('degen', 'easy', 'What does ''whale'' mean?', '["Small investor","Scammer","Large holder with significant influence","Developer"]'::jsonb, 2),
('memecoins', 'easy', 'What animal is SAMO based on?', '["Cat","Dog (Samoyed)","Monkey","Bear"]'::jsonb, 1),
('technical', 'hard', 'What is the current inflation rate of SOL (approximately)?', '["0%","1.5%","5%","8%"]'::jsonb, 2),
('influencers', 'medium', 'Which influencer focuses on NFTs and digital art?', '["Varies by person","Threadguy","Orangie","Jakey"]'::jsonb, 0),
('degen', 'medium', 'What does ''cope'' mean in crypto slang?', '["Celebrating wins","Taking profit","Buying more","Denial/rationalization after losses"]'::jsonb, 3),
('technical', 'easy', 'What is Phantom?', '["A Solana wallet","A memecoin","A DEX","An NFT"]'::jsonb, 0),
('seeker', 'hard', 'What is the screen size of the Seeker device?', '["5.5 inches","6.1 inches","6.7 inches","6.36 inches"]'::jsonb, 3),
('og_lore', 'medium', 'What inspired the name ''Solana''?', '["Solana Beach, California","Solar energy","A person''s name","Random generation"]'::jsonb, 0),
('defi', 'easy', 'What does ''liquidity pool'' mean?', '["Swimming pool NFT","Tokens locked for trading pairs","Staking rewards","Validator pool"]'::jsonb, 1),
('memecoins', 'medium', 'Which platform competes directly with Pump.fun?', '["BonkFun","Raydium","Orca","Jupiter"]'::jsonb, 0),
('degen', 'easy', 'What does ''to the moon'' mean?', '["Price will crash","Price will skyrocket","Selling","Staking"]'::jsonb, 1),
('technical', 'medium', 'What is a validator on Solana?', '["Smart contract","Node that processes transactions","Token standard","Wallet type"]'::jsonb, 1),
('influencers', 'hard', 'Which influencer was early to both SOL and WIF?', '["Ansem","Threadguy","Orangie","Jakey"]'::jsonb, 0),
('og_lore', 'easy', 'What year was the Solana whitepaper first published?', '["2016","2018","2017","2019"]'::jsonb, 2),
('defi', 'hard', 'What is Mango Markets?', '["NFT marketplace","DEX","Lending protocol","Defunct DeFi protocol (exploited)"]'::jsonb, 3),
('degen', 'medium', 'What does ''shitcoin'' mean?', '["Bitcoin","Low-quality token with no value","Memecoin","Stablecoin"]'::jsonb, 1),
('technical', 'easy', 'What is the Solana Explorer used for?', '["Gaming","Trading","Viewing blockchain transactions","Staking"]'::jsonb, 2),
('memecoins', 'easy', 'What year did BONK launch?', '["2020","2021","2023","2022"]'::jsonb, 3),
('seeker', 'medium', 'What is Minty on Seeker?', '["A game","DeFi app","Built-in NFT marketplace","Wallet"]'::jsonb, 2),
('degen', 'easy', 'What does ''NGMI'' mean?', '["Never Gonna Make It","New Great Market Investment","Next Generation Mining","No Good Money Income"]'::jsonb, 0),
('technical', 'hard', 'What is the Solana Virtual Machine called?', '["EVM","SOL-VM","SolVM","SVM"]'::jsonb, 3),
('og_lore', 'medium', 'What company did Raj Gokal work at before Solana?', '["Omada Health","Google","Facebook","Qualcomm"]'::jsonb, 0),
('defi', 'medium', 'What is Solend?', '["DEX","NFT marketplace","Wallet","Algorithmic lending protocol"]'::jsonb, 3),
('influencers', 'easy', 'What platform do most crypto influencers use for long-form content?', '["Instagram","X threads","Facebook","Reddit"]'::jsonb, 1),
('memecoins', 'hard', 'What percentage of BONK was burned in 2023?', '["5%","15%","25%","30%+"]'::jsonb, 3),
('degen', 'medium', 'What does ''bagholder'' mean?', '["Successful investor","Exchange operator","Someone stuck holding worthless tokens","Whale"]'::jsonb, 2),
('technical', 'medium', 'What is the command to install Solana CLI?', '["npm install solana","cargo install solana","sh -c \"$(curl -sSfL https://release.solana.com/...)","brew install solana"]'::jsonb, 2),
('seeker', 'easy', 'What is the Saga/Seeker bonus program called?', '["Chapter 2","Solana Rewards","Web3 Bonus","Crypto Cash"]'::jsonb, 0),
('og_lore', 'hard', 'What was the FTX collapse''s impact on Solana?', '["Price crashed from ~$30 to ~$8","No impact","Solana shut down","Price increased"]'::jsonb, 0),
('defi', 'easy', 'What is impermanent loss?', '["Temporary loss from price divergence in LP","Guaranteed loss","Permanent loss","Staking penalty"]'::jsonb, 0),
('degen', 'easy', 'What does ''LFG'' stand for?', '["Let''s Find Gold","Long Form Growth","Liquidity For Gains","Let''s F***ing Go"]'::jsonb, 3),
('memecoins', 'medium', 'What was unique about BONK''s distribution?', '["Airdropped to Solana community","ICO","Mined","Pre-sold to VCs"]'::jsonb, 0),
('technical', 'easy', 'What does RPC stand for?', '["Remote Procedure Call","Rapid Processing Center","Random Protocol Chain","Reward Pool Contract"]'::jsonb, 0),
('influencers', 'medium', 'What is ''Jakey'' known for?', '["Technical analysis","NFT trading","Memecoin calls","DeFi strategies"]'::jsonb, 2),
('og_lore', 'medium', 'What major event happened to Solana in September 2021?', '["Network outage","ATH price","Rebranding","Merger"]'::jsonb, 0),
('defi', 'medium', 'What is the main risk in yield farming?', '["Impermanent loss & smart contract risk","No risk","Too much profit","Network fees"]'::jsonb, 0),
('degen', 'hard', 'What does ''ser this is a Wendy''s'' mean?', '["Food recommendation","Scam warning","Bullish indicator","Humorous way to say you''re being too serious/technical"]'::jsonb, 3),
('technical', 'medium', 'What is Anchor in Solana development?', '["A wallet","A DEX","A framework for building Solana programs","A token standard"]'::jsonb, 2),
('seeker', 'hard', 'What is the battery capacity of Seeker?', '["3,000 mAh","5,000 mAh","4,000 mAh","6,000 mAh"]'::jsonb, 1),
('memecoins', 'easy', 'What does ''memecoin'' mean?', '["Token created as a joke/meme","Serious utility token","NFT","Stablecoin"]'::jsonb, 0),
('og_lore', 'easy', 'What is Solana''s unofficial mascot?', '["Bonk dog","Lion","Eagle","Cat"]'::jsonb, 0),
('defi', 'hard', 'What is the difference between Jupiter and Raydium?', '["No difference","Jupiter is aggregator, Raydium is DEX","Jupiter is older","Different blockchains"]'::jsonb, 1),
('degen', 'medium', 'What does ''aped in'' mean?', '["Careful research","Sold everything","Bought impulsively without research","Staked tokens"]'::jsonb, 2),
('technical', 'easy', 'What is Solscan?', '["Security tool","Wallet","DEX","Block explorer"]'::jsonb, 3),
('influencers', 'hard', 'Which influencer is associated with the phrase ''rotational''?', '["Threadguy","Ansem","Orangie","Supabased"]'::jsonb, 1),
('seeker', 'medium', 'What does the Seeker Seed Vault do?', '["Stores NFTs","Mining","Staking","Secure offline seed phrase storage"]'::jsonb, 3),
('memecoins', 'medium', 'What makes Pump.fun different from traditional DEXs?', '["No difference","Better security","Lower fees","Bonding curve launchpad for memecoins"]'::jsonb, 3),
('degen', 'easy', 'What does ''bearish'' mean?', '["Expecting price to go up","Neutral","Confused","Expecting price to go down"]'::jsonb, 3),
('technical', 'hard', 'What is the purpose of the System Program on Solana?', '["Fundamental operations like account creation","Create memecoins","NFT minting","Staking"]'::jsonb, 0),
('og_lore', 'medium', 'What major VC firm backed Solana early?', '["Sequoia","Y Combinator","Tiger Global","a16z (Andreessen Horowitz)"]'::jsonb, 3),
('defi', 'medium', 'What is slippage in trading?', '["Transaction fee","Profit margin","Staking reward","Difference between expected and actual price"]'::jsonb, 3),
('degen', 'easy', 'What does ''bullish'' mean?', '["Expecting price to go up","Expecting price to go down","Neutral","Selling"]'::jsonb, 0),
('memecoins', 'hard', 'What was the controversy with BonkFun launch?', '["Rug pull","Accusations of copying Pump.fun code","No controversy","Wrong blockchain"]'::jsonb, 1),
('technical', 'medium', 'What is a PDA in Solana?', '["Personal Data Access","Program Derived Address","Public Decentralized Account","Protocol Development API"]'::jsonb, 1),
('seeker', 'easy', 'What operating system does Seeker use?', '["Android","iOS","Custom Linux","Windows Phone"]'::jsonb, 0),
('influencers', 'medium', 'What is Ansem''s real name speculation?', '["John Doe","Michael Smith","Chris Johnson","Never revealed/confirmed"]'::jsonb, 3),
('og_lore', 'hard', 'How many co-founders did Solana originally have?', '["3","1","2","5"]'::jsonb, 0),
('defi', 'easy', 'What does ''staking'' mean?', '["Selling","Trading","Buying","Locking tokens to earn rewards"]'::jsonb, 3),
('degen', 'medium', 'What does ''send it'' mean?', '["Transfer tokens","Sell","Go all in/take the risk","Wait"]'::jsonb, 2),
('memecoins', 'easy', 'What color is the BONK logo primarily?', '["Blue","Orange/Red","Green","Purple"]'::jsonb, 1),
('technical', 'easy', 'What does SOL stand for?', '["Speed Of Light","Source Of Liquidity","System Operating Layer","Solana''s native token"]'::jsonb, 3),
('seeker', 'hard', 'What is the retail price of Seeker?', '["$199","$299","$450","$399"]'::jsonb, 2),
('og_lore', 'medium', 'What was Solana''s peak price in 2021?', '["$100","$150","$200","$260"]'::jsonb, 3),
('defi', 'hard', 'What happened to Serum DEX after FTX collapse?', '["Nothing changed","Forked to OpenBook","Shut down completely","Moved to Ethereum"]'::jsonb, 1),
('degen', 'hard', 'What does ''up only'' mean?', '["Conservative strategy","Bearish indicator","Selling strategy","Sarcastic/optimistic phrase about price only going up"]'::jsonb, 3),
('memecoins', 'medium', 'What blockchain was WIF originally on?', '["Ethereum","Solana","BSC","Polygon"]'::jsonb, 1),
('technical', 'medium', 'What is the Solana token program ID?', '["Token2022","TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA","SPL-Token","SolToken"]'::jsonb, 1),
('influencers', 'easy', 'What do crypto influencers often share?', '["Trade calls and market analysis","Recipes","Travel photos","Pet videos"]'::jsonb, 0),
('og_lore', 'easy', 'What does Solana aim to solve?', '["Privacy","Mining","Governance","Scalability"]'::jsonb, 3),
('nfts', 'medium', 'Which NFT marketplace overtook Magic Eden as the top marketplace on Solana by volume?', '["OpenSea","Blur","Tensor","Solanart"]'::jsonb, 2),
('nfts', 'easy', 'What are ''compressed NFTs'' on Solana designed to do?', '["Make images smaller","Compress blockchain data","Speed up transfers","Reduce minting costs by up to 99%"]'::jsonb, 3),
('nfts', 'medium', 'Which Solana NFT collection was created by the Backpack team and features xNFT technology?', '["Mad Lads","DeGods","Okay Bears","Claynosaurz"]'::jsonb, 0),
('nfts', 'hard', 'What technology do compressed NFTs on Solana use to store data efficiently?', '["Concurrent Merkle trees","IPFS pinning","Arweave bundling","Zero-knowledge proofs"]'::jsonb, 0),
('nfts', 'easy', 'What protocol is the standard for creating and managing NFTs on Solana?', '["OpenZeppelin","Metaplex","ERC-721","Coral"]'::jsonb, 1),
('nfts', 'medium', 'Which Solana NFT collection features animated dinosaur characters?', '["Mad Lads","Okay Bears","Famous Fox Federation","Claynosaurz"]'::jsonb, 3),
('nfts', 'hard', 'What did DeGods do that shocked the Solana NFT community in late 2022?', '["Rugged the project","Migrated to Ethereum","Burned all NFTs","Launched a token"]'::jsonb, 1),
('nfts', 'medium', 'What is the Tensor airdrop token called?', '["TENS","TENSOR","TNSR","TNS"]'::jsonb, 2),
('nfts', 'easy', 'What does ''floor price'' mean in NFT trading?', '["The lowest listed price in a collection","The highest sale price","The average price","The minting price"]'::jsonb, 0),
('nfts', 'hard', 'What is an xNFT as pioneered by the Backpack wallet?', '["An extra-large NFT","An executable NFT that runs code like an app","A cross-chain NFT","An expired NFT"]'::jsonb, 1),
('bitcoin', 'easy', 'What is the maximum supply of Bitcoin?', '["18 million","21 million","100 million","Unlimited"]'::jsonb, 1),
('bitcoin', 'easy', 'Who is credited with creating Bitcoin?', '["Vitalik Buterin","Satoshi Nakamoto","Charles Hoskinson","Nick Szabo"]'::jsonb, 1),
('bitcoin', 'medium', 'In what month and year was the first US spot Bitcoin ETF approved?', '["January 2024","October 2023","March 2024","June 2024"]'::jsonb, 0),
('bitcoin', 'medium', 'When did the most recent Bitcoin halving occur?', '["May 2020","November 2023","April 2024","January 2025"]'::jsonb, 2),
('bitcoin', 'hard', 'After the April 2024 halving, what is the current Bitcoin block reward?', '["6.25 BTC","3.125 BTC","1.5625 BTC","12.5 BTC"]'::jsonb, 1),
('bitcoin', 'easy', 'What is the Lightning Network?', '["A Bitcoin mining pool","A Layer 2 solution for fast Bitcoin payments","An altcoin","A Bitcoin wallet"]'::jsonb, 1),
('bitcoin', 'hard', 'What was the name of the largest crypto exchange that collapsed in November 2022?', '["Binance","Coinbase","FTX","Kraken"]'::jsonb, 2),
('bitcoin', 'medium', 'What is a ''Bitcoin halving''?', '["Bitcoin''s price drops 50%","Half of Bitcoin is burned","Mining difficulty is halved","Block rewards are cut in half roughly every 4 years"]'::jsonb, 3),
('bitcoin', 'hard', 'Which protocol upgrade enabled NFT-like ''Ordinals'' inscriptions on Bitcoin?', '["Taproot","SegWit","Lightning","Schnorr only"]'::jsonb, 0),
('bitcoin', 'medium', 'Which asset manager manages the largest spot Bitcoin ETF by AUM (iShares Bitcoin Trust)?', '["Grayscale","BlackRock","Fidelity","VanEck"]'::jsonb, 1),
('ecosystem', 'medium', 'What does Jito Labs provide to the Solana ecosystem?', '["NFT marketplace","Stablecoin protocol","MEV-optimized validator client and liquid staking","Cross-chain bridge"]'::jsonb, 2),
('ecosystem', 'easy', 'What is Pyth Network?', '["A DEX","A decentralized oracle providing real-time price feeds","A lending protocol","A memecoin launchpad"]'::jsonb, 1),
('ecosystem', 'medium', 'What real-world network migrated from its own blockchain to Solana in 2023?', '["Chainlink","The Graph","Filecoin","Helium"]'::jsonb, 3),
('ecosystem', 'hard', 'What does Wormhole do in the Solana ecosystem?', '["Mines SOL","Creates memecoins","Runs validators","Provides cross-chain messaging and token bridging"]'::jsonb, 3),
('ecosystem', 'easy', 'What does Marinade Finance allow users to do?', '["Trade memecoins","Mint NFTs","Bridge to Ethereum","Liquid stake SOL and receive mSOL"]'::jsonb, 3),
('ecosystem', 'medium', 'What is Render Network, which moved to Solana?', '["A gaming platform","An NFT marketplace","A decentralized GPU rendering network","A lending protocol"]'::jsonb, 2),
('ecosystem', 'hard', 'What does Hivemapper use Solana for?', '["Social media","Cloud storage","Music streaming","Decentralized mapping with dashcam contributors earning HONEY tokens"]'::jsonb, 3),
('ecosystem', 'medium', 'What is Jito''s liquid staking token called?', '["jSOL","stJITO","JitoSOL","jstSOL"]'::jsonb, 2),
('ecosystem', 'easy', 'What type of data does Pyth Network primarily provide?', '["Weather data","Social media sentiment","Financial market price data","Blockchain analytics"]'::jsonb, 2),
('ecosystem', 'hard', 'How much was stolen in the Wormhole bridge exploit of February 2022?', '["$50 million","$320 million","$120 million","$600 million"]'::jsonb, 1),
('recent_news', 'medium', 'Which company is building the Firedancer validator client for Solana?', '["Solana Labs","Coinbase","Jump Crypto","Paradigm"]'::jsonb, 2),
('recent_news', 'hard', 'What programming language is the Firedancer validator client primarily written in?', '["C/C++","Rust","Go","Java"]'::jsonb, 0),
('recent_news', 'medium', 'Which major asset manager filed for a spot Solana ETF in the United States?', '["BlackRock","VanEck","Vanguard","Fidelity"]'::jsonb, 1),
('recent_news', 'hard', 'What is the name of the lightweight Firedancer variant released first as a stepping stone?', '["MiniDancer","LiteDancer","Frankendancer","FastDancer"]'::jsonb, 2),
('recent_news', 'medium', 'In which country was the first spot Solana ETF approved and launched?', '["United States","Brazil","Germany","Canada"]'::jsonb, 3),
('recent_news', 'easy', 'What is the name of Jupiter''s governance token?', '["JUPI","JPTR","JUP","JUPITER"]'::jsonb, 2),
('recent_news', 'medium', 'What new feature did Jupiter launch allowing users to set recurring buys?', '["Jupiter Swap","Jupiter Auto","Jupiter DCA (Dollar Cost Average)","Jupiter Schedule"]'::jsonb, 2),
('recent_news', 'hard', 'What is Solana''s QUIC protocol used for?', '["Transaction ingestion replacing UDP","Smart contract execution","NFT minting","Validator voting"]'::jsonb, 0),
('recent_news', 'easy', 'Which Solana wallet became the most downloaded crypto app on iOS in 2024?', '["Phantom","Solflare","Backpack","Glow"]'::jsonb, 0),
('recent_news', 'medium', 'What is the name of the annual Solana conference, most recently held in Singapore?', '["SolCon","Breakpoint","Solana Summit","SolFest"]'::jsonb, 1),
('recent_news', 'easy', 'Which stablecoin surpassed $2 billion in supply on Solana by 2024?', '["DAI","USDT","USDC","BUSD"]'::jsonb, 2),
('degen_culture', 'easy', 'What does ''CT'' stand for in crypto slang?', '["Crypto Token","Crypto Twitter","Central Trading","Chain Technology"]'::jsonb, 1),
('degen_culture', 'medium', 'What does ''rugged'' mean in crypto?', '["Got a great deal","Made a profit","Was scammed when developers pulled liquidity","Completed a trade"]'::jsonb, 2),
('degen_culture', 'easy', 'What does ''giga brain'' mean in crypto slang?', '["Someone who lost money","A type of token","Someone who is extremely smart or made a genius trade","A hardware wallet"]'::jsonb, 2),
('degen_culture', 'medium', 'What does ''touch grass'' mean when told to someone on CT?', '["Buy more crypto","Go outside and take a break from screens","Research green tokens","Start farming yields"]'::jsonb, 1),
('degen_culture', 'hard', 'What does ''cope and seethe'' mean in crypto culture?', '["A trading strategy","To celebrate gains","A DeFi protocol name","To rationalize losses while being angry about them"]'::jsonb, 3),
('degen_culture', 'easy', 'What is a ''dApp''?', '["Digital Application Protocol","Data Access Point","Distributed Analysis Program","Decentralized Application"]'::jsonb, 3),
('degen_culture', 'medium', 'What does ''larping'' mean in crypto?', '["Playing blockchain games","Pretending to be something you''re not (e.g., pretending to be rich)","Learning a new protocol","Running a validator"]'::jsonb, 1),
('degen_culture', 'hard', 'What does ''the flippening'' refer to?', '["When another crypto surpasses Bitcoin in market cap","When memecoins flip DeFi","When NFTs flip tokens","When Solana beats Ethereum in TVL"]'::jsonb, 0),
('degen_culture', 'easy', 'What does ''NFA'' stand for?', '["New Financial Asset","National Futures Association","Not Financial Advice","No Funds Available"]'::jsonb, 2),
('degen_culture', 'medium', 'What is a ''honeypot'' scam in crypto?', '["A sweet DeFi deal","A bee-themed NFT","A token you can buy but cannot sell","A staking reward trap"]'::jsonb, 2),
('advanced_technical', 'hard', 'What are Solana Token Extensions (Token-2022) designed for?', '["Adding features like transfer fees and confidential transfers natively","Faster memecoins","Replacing SPL tokens entirely","Cross-chain compatibility only"]'::jsonb, 0),
('advanced_technical', 'hard', 'What is state compression on Solana primarily used to reduce?', '["On-chain storage costs using Merkle trees","Transaction speed","Validator hardware requirements","Token supply"]'::jsonb, 0),
('advanced_technical', 'hard', 'What do Address Lookup Tables (ALTs) on Solana allow?', '["Finding wallet owners'' identities","Looking up token prices","Including more accounts in a single transaction by referencing addresses compactly","Mapping domain names to wallets"]'::jsonb, 2),
('advanced_technical', 'hard', 'What are priority fees on Solana used for?', '["Paying for NFT mints","Unlocking premium features","Reducing slippage on DEXs","Incentivizing validators to include your transaction sooner during congestion"]'::jsonb, 3),
('advanced_technical', 'hard', 'What is a ''local fee market'' on Solana?', '["Regional pricing for transactions","Fee competition isolated to specific accounts/programs, not the whole network","A marketplace for trading fees","Validator-specific pricing"]'::jsonb, 1),
('recent_news', 'medium', 'What approximate all-time high did Solana reach in January 2025?', '["$176","$293","$220","$350"]'::jsonb, 1),
('recent_news', 'medium', 'What did Solana Pay integration with Shopify enable merchants to do?', '["Accept USDC payments at checkout","Mine SOL","Create NFTs","Stake customer deposits"]'::jsonb, 0);

-- Verify count
SELECT count(*) AS total_practice_questions FROM practice_questions;
